# This is a basic workflow to help you get started with Actions

name: auto-close PRs

# Controls when the workflow will run
on:
  pull_request_target:
    types:
      - opened
    branches:
      - 'phase4'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_if:
    if:  startsWith(github.head_ref, 'phase4_v2')
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        # Optional. Post a issue comment just before closing a pull request.
        comment: "sample"
